version: "3"
services:
  app:
    container_name: airpol
    restart: always
    build: .
    ports:
      - "10000:10000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
